In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score
import pickle
# Regression Models
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,Ridge,RidgeCV,Lasso,LassoLars,BayesianRidge,TweedieRegressor,Perceptron
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor

In [2]:
day_wise_df = pd.read_csv('day_wise.csv')
# all_data_df = pd.read_csv('full_grouped.csv')

In [3]:
del day_wise_df['No. of countries']
day_wise_df.head()

Date  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0  2020-01-22        555      17         28     510          0           0   
1  2020-01-23        654      18         30     606         99           1   
2  2020-01-24        941      26         36     879        287           8   
3  2020-01-25       1434      42         39    1353        493          16   
4  2020-01-26       2118      56         52    2010        684          14   

   New recovered  
0              0  
1              2  
2              6  
3              3  
4             13

In [4]:
len(day_wise_df)

188

In [5]:
date_list_day_wise_df = day_wise_df['Date']

In [6]:
date_list_day_wise_df

0      2020-01-22
1      2020-01-23
2      2020-01-24
3      2020-01-25
4      2020-01-26
          ...    
183    2020-07-23
184    2020-07-24
185    2020-07-25
186    2020-07-26
187    2020-07-27
Name: Date, Length: 188, dtype: object

In [7]:
date_list_day_wise_df_final = []
for a in date_list_day_wise_df:
    date_list_day_wise_df_final.append(a.replace('-',''))

In [8]:
len(date_list_day_wise_df_final)

188

In [9]:
day_wise_df['Date'] = date_list_day_wise_df_final

In [10]:
X = day_wise_df.drop(['New cases','New deaths','New recovered','Active','Deaths','Recovered','Confirmed'],axis=1)
# y = day_wise_df['Deaths']
y = day_wise_df.drop(['Date'],axis=1)

In [11]:
y

Confirmed  Deaths  Recovered   Active  New cases  New deaths  \
0          555      17         28      510          0           0   
1          654      18         30      606         99           1   
2          941      26         36      879        287           8   
3         1434      42         39     1353        493          16   
4         2118      56         52     2010        684          14   
..         ...     ...        ...      ...        ...         ...   
183   15510481  633506    8710969  6166006     282756        9966   
184   15791645  639650    8939705  6212290     281164        6144   
185   16047190  644517    9158743  6243930     255545        4867   
186   16251796  648621    9293464  6309711     204606        4104   
187   16480485  654036    9468087  6358362     228693        5415   

     New recovered  
0                0  
1                2  
2                6  
3                3  
4               13  
..             ...  
183         169714  
184         228736  
185         219038  
186         134721  
187         174623  

[188 rows x 7 columns]

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train

Date
179  20200719
100  20200501
69   20200331
134  20200604
136  20200606
..        ...
2    20200124
159  20200629
107  20200508
58   20200320
35   20200226

[150 rows x 1 columns]

In [13]:
model_KNeighborsRegressor = KNeighborsRegressor()
model_KNeighborsRegressor.fit(X_train,y_train)
model_KNeighborsRegressor.score(X_test,y_test)

0.9572782372937907

In [14]:
model_BaggingRegressor = BaggingRegressor()
model_BaggingRegressor.fit(X_train,y_train)
model_BaggingRegressor.score(X_test,y_test)

0.9609064601708622

In [15]:
model_RandomForestRegressor = RandomForestRegressor()
model_RandomForestRegressor.fit(X_train,y_train)
model_RandomForestRegressor.score(X_test,y_test)

0.9636775336248996

In [16]:
info = np.array([20200408,1497624,322017,1081957,83775,6735,28352])

In [17]:
info_df = pd.DataFrame(info)

In [18]:
info_df = info_df.T

In [19]:
[93650.00000104],[86915]

([93650.00000104], [86915])

In [20]:
day_wise_df.iloc[69]

Date             20200331
Confirmed          871355
Deaths              44478
Recovered          174074
Active             652803
New cases           76416
New deaths           4844
New recovered       12367
Name: 69, dtype: object

In [21]:
info_df[0] = 20200331
info_df[1] = 871355
info_df[2] = 174074
info_df[3] = 652803
info_df[4] = 76416
info_df[5] = 4844
info_df[6] = 12367

In [22]:
print(model_BaggingRegressor.predict(info_df))
print(model_BayesianRidge.predict(info_df))
print(model_KNeighborsRegressor.predict(info_df))
print(model_Lasso.predict(info_df))
print(model_LassoLars.predict(info_df))
print(model_LinearRegression.predict(info_df))
print(model_RandomForestRegressor.predict(info_df))
print(model_Ridge.predict(info_df))
print(model_TweedieRegressor.predict(info_df))

[[773665.3         38751.63333333 158562.90833333 576350.75833333
   66880.18333333   4175.21666667  12039.78333333]]


NameError: name 'model_BayesianRidge' is not defined

In [23]:
print(model_BayesianRidge.predict(info_df))
print(model_LinearRegression.predict(info_df))

NameError: name 'model_BayesianRidge' is not defined

In [24]:
choice = random.choice(range(187))
print(choice)
day_wise_df.iloc[choice].drop('Deaths')

NameError: name 'random' is not defined

In [25]:
info_df[0] = 20200503
info_df[1] = 3515244
info_df[2] = 1097577
info_df[3] = 2169008
info_df[4] = 77636
info_df[5] = 3453
info_df[6] = 31215

In [26]:
day_wise_df.iloc[102]

Date             20200503
Confirmed         3515244
Deaths             248659
Recovered         1097577
Active            2169008
New cases           77636
New deaths           3453
New recovered       31215
Name: 102, dtype: object

In [27]:
model_KNeighborsRegressor = KNeighborsRegressor()
model_KNeighborsRegressor.fit(X_train,y_train)
model_KNeighborsRegressor.score(X_test,y_test)


0.9572782372937907

In [28]:
del info_df

In [29]:
array = np.array([20200331])
df = pd.DataFrame(array)

In [30]:
df.T

0
0  20200331

In [31]:
model_KNeighborsRegressor.predict(df)

array([[721196.6,  35275.8, 147729.2, 538191.6,  66249.8,   3833.4,
         10785. ]])

In [32]:
# Confirmed	Deaths	Recovered	Active	New cases	New deaths	New recovered

In [33]:
model_BaggingRegressor.predict(df)

array([[773665.3       ,  38751.63333333, 158562.90833333,
        576350.75833333,  66880.18333333,   4175.21666667,
         12039.78333333]])

In [34]:
model_RandomForestRegressor.predict(df)

array([[816176.8775    ,  41050.83083333, 164265.39083333,
        610860.65583333,  70896.56333333,   4414.90166667,
         12163.95083333]])

In [35]:
pickle.dump(model_KNeighborsRegressor,open('model_KNeighborsRegressor.pkl','wb'))
pickle.dump(model_BaggingRegressor,open('model_BaggingRegressor.pkl','wb'))
pickle.dump(model_RandomForestRegressor,open('model_RandomForestRegressor.pkl','wb'))

In [36]:
day_wise_df.loc[day_wise_df['Date'] == '20200331']

Date  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
69  20200331     871355   44478     174074  652803      76416        4844   

    New recovered  
69          12367

In [ ]:
pred_1 = model_RandomForestRegressor.predict(X_test)
pred_2 = model_BaggingRegressor.predict(X_test)
pred_3 = model_KNeighborsRegressor.predict(X_test)
print(accuracy_score(pred_1,y_test))
print(accuracy_score(pred_2,y_test))
print(accuracy_score(pred_1,y_test))
